#!/bin/bash
case "$1" in
  "smash" )
    node ./smash.js $2;;
  "prepare" )
    node prepare.js ;;
  "destroy" )
    node destroy.js ;;
  "lookup" )
    node ./lookup.js $2;;
  "recover" )
    gulp default ;;
  "watch" )
    gulp watch ;;
  "help" )
    node ./help.js ;;
  "deploy" )
    phantomjs --web-security=false --ignore-ssl-errors=true --cookies-file=cookies.txt deploy.js $2;;
esac
