#!/bin/bash
case "$1" in
  "smash" )
    node ./smash.js $2;;
  "prepare" )
    ./prepare.sh ;;
  "destroy" )
    ./destroy.sh ;;
  "lookup" )
    node ./lookup.js $2;;
  "recover" )
    gulp default ;;
  "watch" )
    gulp watch ;;
  "help" )
    node ./help.js ;;
# TODO
 "deploy" )
   node ./deploy.js default_frontend_stylesheet;;
esac
